import React, { useState, useEffect } from 'react';
import type { CircuitNode, NodeType } from '../types/logic';
import {
  calculatePracticalMetrics,
  generatePracticalWaveformPoints,
  AMPLIFIER_LAB_SPECS,
  type PracticalAmpParams,
  type PracticalAmpMetrics,
  type WaveformPoint,
} from '../engine/AmplifierEngine';
import { Activity, X, Play, Pause, BarChart2, FileText, Download, Target, CheckCircle2 } from 'lucide-react';

interface AmplifierLabModalProps {
  nodes: CircuitNode[];
  selectedNodeId: string | null;
  onClose: () => void;
}

export const AmplifierLabModal: React.FC<AmplifierLabModalProps> = ({ onClose }) => {
  const [activeTab, setActiveTab] = useState<'waveforms' | 'loadline' | 'table' | 'manual'>('waveforms');

  // Amplifier Lab Parameters
  const [selectedAmpType, setSelectedAmpType] = useState<NodeType>('AMP_CLASS_A');
  const [params, setParams] = useState<PracticalAmpParams>(AMPLIFIER_LAB_SPECS['AMP_CLASS_A'].defaultParams);

  // Live Sweep Animation
  const [isLiveAnim, setIsLiveAnim] = useState<boolean>(true);
  const [animOffset, setAnimOffset] = useState<number>(0);

  // Sync default params when switching class
  const handleSelectAmpClass = (type: NodeType) => {
    setSelectedAmpType(type);
    const spec = AMPLIFIER_LAB_SPECS[type];
    if (spec) {
      setParams({ ...spec.defaultParams });
    }
  };

  useEffect(() => {
    if (!isLiveAnim) return;
    const timer = setInterval(() => {
      setAnimOffset((prev) => (prev + 15) % 1000);
    }, 40);
    return () => clearInterval(timer);
  }, [isLiveAnim]);

  const currentSpec = AMPLIFIER_LAB_SPECS[selectedAmpType] || AMPLIFIER_LAB_SPECS['AMP_CLASS_A'];
  const metrics: PracticalAmpMetrics = calculatePracticalMetrics(params);
  const wavePoints: WaveformPoint[] = generatePracticalWaveformPoints(params, 180, animOffset);

  // SVG Canvas dimensions
  const svgW = 560;
  const svgH = 220;
  const pad = 30;

  // Build SVG path strings
  const buildTimeDomainPath = (key: 'vIn' | 'vOut' | 'pwmVal') => {
    const periodMs = 1000 / params.freqHz;
    return wavePoints
      .map((p, idx) => {
        const val = p[key] ?? 0;
        const x = pad + ((p.time % (2 * periodMs)) / (2 * periodMs)) * (svgW - 2 * pad);
        const y = svgH / 2 - (val / (params.vcc * 0.6)) * (svgH / 2 - pad);
        return `${idx === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(' ');
  };

  // Build X-Y Transfer Characteristic Path (Vin vs Vout)
  const buildTransferCurvePath = () => {
    return wavePoints
      .map((p, idx) => {
        const x = svgW / 2 + (p.vIn / (params.vinPeak * 1.3)) * (svgW / 2 - pad);
        const y = svgH / 2 - (p.vOut / (metrics.vcc * 0.6)) * (svgH / 2 - pad);
        return `${idx === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(' ');
  };

  // Export Practical Lab Report Text File
  const handleExportLabReport = () => {
    const reportText = `========================================================================
VIRTUAL ELECTRONICS LAB REPORT: POWER AMPLIFIER CHARACTERISTICS
========================================================================
Date: ${new Date().toLocaleString()}
Experiment: Performance Analysis of ${currentSpec.name}

1. AMPLIFIER SPECIFICATIONS & SETTINGS:
   - Amplifier Class: ${currentSpec.name} (Class ${currentSpec.classLetter})
   - VCC Supply Voltage: ${metrics.vcc} V
   - Load Resistance (RL): ${metrics.rLoad} Ohms
   - Input Signal Amplitude: ${metrics.vInPeak} V Peak (${metrics.vInRms} V RMS)
   - Input Frequency: ${params.freqHz} Hz
   - Desired Voltage Gain (Av): ${params.gain}x

2. MEASURED PRACTICAL RESULTS & METRICS:
   - Peak Output Voltage (Vout,pk): ${metrics.vOutPeak} V
   - RMS Output Voltage (Vout,rms): ${metrics.vOutRms} V
   - Measured Voltage Gain (Av): ${metrics.voltageGain} (${metrics.voltageGainDb} dB)
   - Power Gain (Ap): ${metrics.powerGainDb} dB
   - AC Output Power (Pout): ${metrics.pOutMw} mW
   - DC Supply Power (Pdc): ${metrics.pDcMw} mW
   - Transistor Power Dissipation (Pd): ${metrics.pDissipationMw} mW
   - Collector Efficiency (η): ${metrics.efficiency} %
   - Total Harmonic Distortion (THD): ${metrics.thdPercent} %
   - Conduction Angle (θ): ${metrics.conductionAngleDeg}°
   - Q-Point Operating State: VCEQ = ${metrics.vCeq} V, ICQ = ${metrics.iCqMa} mA

3. OBSERVATIONS & CONCLUSION:
   - Conduction Mode: ${currentSpec.conductionAngle}
   - Theoretical Max Efficiency: ${currentSpec.typicalEfficiency}
   - Observations: ${currentSpec.description}

========================================================================
Report generated by Logic.ly Virtual Electronics Lab Simulator.
========================================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Lab_Report_${selectedAmpType}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.75)',
        backdropFilter: 'blur(8px)',
        zIndex: 90,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
      }}
      onClick={onClose}
    >
      <div
        className="glass-panel"
        style={{
          width: '100%',
          maxWidth: '820px',
          maxHeight: '92vh',
          borderRadius: '16px',
          padding: '22px',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 24px 48px rgba(0,0,0,0.6)',
          border: '1px solid var(--border-color)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '14px', borderBottom: '1px solid var(--border-color)', paddingBottom: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{ padding: '8px', borderRadius: '10px', background: 'rgba(56, 189, 248, 0.15)', color: 'var(--accent-cyan)' }}>
              <Activity size={22} />
            </div>
            <div>
              <h2 style={{ fontSize: '1.15rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                Power Amplifiers Practical Workbench
              </h2>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                Interactive Virtual Electronics Lab: Waveforms, Q-Point Loadline, Measurements & FFT Analysis
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '6px', borderRadius: '6px' }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Class Selection Buttons */}
        <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap', marginBottom: '14px' }}>
          {Object.values(AMPLIFIER_LAB_SPECS).map((spec) => (
            <button
              key={spec.type}
              onClick={() => handleSelectAmpClass(spec.type)}
              style={{
                padding: '6px 12px',
                borderRadius: '8px',
                fontSize: '0.8rem',
                fontWeight: selectedAmpType === spec.type ? 700 : 500,
                border: `1px solid ${selectedAmpType === spec.type ? spec.color : 'var(--border-color)'}`,
                background: selectedAmpType === spec.type ? `${spec.color}25` : 'var(--bg-card)',
                color: selectedAmpType === spec.type ? spec.color : 'var(--text-secondary)',
                cursor: 'pointer',
                transition: 'all 0.15s ease',
              }}
            >
              {spec.name}
            </button>
          ))}
        </div>

        {/* Navigation Tabs */}
        <div style={{ display: 'flex', gap: '8px', marginBottom: '14px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px' }}>
          <button
            onClick={() => setActiveTab('waveforms')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '0.82rem',
              fontWeight: 600,
              border: 'none',
              background: activeTab === 'waveforms' ? 'var(--accent-cyan)' : 'var(--bg-card)',
              color: activeTab === 'waveforms' ? '#0f172a' : 'var(--text-secondary)',
              cursor: 'pointer',
            }}
          >
            <BarChart2 size={16} /> Oscilloscope & Waveform Analysis
          </button>

          <button
            onClick={() => setActiveTab('loadline')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '0.82rem',
              fontWeight: 600,
              border: 'none',
              background: activeTab === 'loadline' ? 'var(--accent-cyan)' : 'var(--bg-card)',
              color: activeTab === 'loadline' ? '#0f172a' : 'var(--text-secondary)',
              cursor: 'pointer',
            }}
          >
            <Target size={16} /> DC Load Line & Q-Point
          </button>

          <button
            onClick={() => setActiveTab('table')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '0.82rem',
              fontWeight: 600,
              border: 'none',
              background: activeTab === 'table' ? 'var(--accent-cyan)' : 'var(--bg-card)',
              color: activeTab === 'table' ? '#0f172a' : 'var(--text-secondary)',
              cursor: 'pointer',
            }}
          >
            <FileText size={16} /> Measurements & Results Table
          </button>

          <button
            onClick={() => setActiveTab('manual')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '6px 14px',
              borderRadius: '8px',
              fontSize: '0.82rem',
              fontWeight: 600,
              border: 'none',
              background: activeTab === 'manual' ? 'var(--accent-cyan)' : 'var(--bg-card)',
              color: activeTab === 'manual' ? '#0f172a' : 'var(--text-secondary)',
              cursor: 'pointer',
            }}
          >
            <CheckCircle2 size={16} /> Practical Worksheet
          </button>
        </div>

        {/* TAB 1: OSCILLOSCOPE & WAVEFORM ANALYSIS */}
        {activeTab === 'waveforms' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', flex: 1, overflowY: 'auto' }}>
            {/* Oscilloscope Graphic Box */}
            <div style={{ borderRadius: '12px', background: '#020617', border: '1px solid var(--border-color)', padding: '14px', position: 'relative' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px', fontSize: '0.78rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                  <span style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>── CH1: Vin ({metrics.vInPeak}V pk)</span>
                  <span style={{ color: currentSpec.color, fontWeight: 700 }}>━━ CH2: Vout ({metrics.vOutPeak}V pk)</span>
                  {selectedAmpType === 'AMP_CLASS_D' && <span style={{ color: '#8b5cf6', fontWeight: 600 }}>┄ PWM Carrier</span>}
                </div>

                <button
                  onClick={() => setIsLiveAnim(!isLiveAnim)}
                  style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', borderRadius: '6px', padding: '4px 8px', fontSize: '0.75rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                >
                  {isLiveAnim ? <Pause size={12} /> : <Play size={12} />}
                  <span>{isLiveAnim ? 'Freeze' : 'Live Sweep'}</span>
                </button>
              </div>

              {/* Time-Domain Waveform Canvas */}
              <svg width="100%" height={svgH} viewBox={`0 0 ${svgW} ${svgH}`} style={{ overflow: 'visible' }}>
                <g stroke="#1e293b" strokeWidth={1} strokeDasharray="4 4">
                  <line x1={pad} y1={pad} x2={svgW - pad} y2={pad} />
                  <line x1={pad} y1={svgH / 2} x2={svgW - pad} y2={svgH / 2} stroke="#334155" strokeWidth={1.5} strokeDasharray="none" />
                  <line x1={pad} y1={svgH - pad} x2={svgW - pad} y2={svgH - pad} />

                  {Array.from({ length: 9 }).map((_, i) => {
                    const vx = pad + (i * (svgW - 2 * pad)) / 8;
                    return <line key={i} x1={vx} y1={pad} x2={vx} y2={svgH - pad} />;
                  })}
                </g>

                {selectedAmpType === 'AMP_CLASS_D' && <path d={buildTimeDomainPath('pwmVal')} fill="none" stroke="#8b5cf6" strokeWidth={1.2} opacity={0.5} />}
                <path d={buildTimeDomainPath('vIn')} fill="none" stroke="var(--accent-cyan)" strokeWidth={2} strokeDasharray="6 4" opacity={0.8} />
                <path d={buildTimeDomainPath('vOut')} fill="none" stroke={currentSpec.color} strokeWidth={3.2} strokeLinecap="round" />
              </svg>
            </div>

            {/* Sub-analysis Grid: Vin vs Vout Transfer Curve + FFT Harmonics */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}>
              {/* Transfer Characteristic Curve (Vin vs Vout) */}
              <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '10px', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px' }}>
                  📈 Vin vs Vout Transfer Characteristic (X-Y Plot)
                </div>
                <div style={{ background: '#020617', borderRadius: '8px', padding: '8px', height: '140px', border: '1px solid var(--border-color)' }}>
                  <svg width="100%" height="124" viewBox={`0 0 ${svgW} ${svgH}`}>
                    <line x1={pad} y1={svgH / 2} x2={svgW - pad} y2={svgH / 2} stroke="#334155" strokeWidth={1} />
                    <line x1={svgW / 2} y1={pad} x2={svgW / 2} y2={svgH - pad} stroke="#334155" strokeWidth={1} />
                    <path d={buildTransferCurvePath()} fill="none" stroke="var(--accent-emerald)" strokeWidth={2.5} />
                  </svg>
                </div>
              </div>

              {/* FFT Harmonic Spectrum Analyzer */}
              <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '10px', border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px', display: 'flex', justifyContent: 'space-between' }}>
                  <span>📊 FFT Harmonic Spectrum</span>
                  <span style={{ color: 'var(--accent-rose)', fontWeight: 600 }}>THD: {metrics.thdPercent}%</span>
                </div>
                <div style={{ background: '#020617', borderRadius: '8px', padding: '10px', height: '140px', display: 'flex', alignItems: 'flex-end', justifyContent: 'space-around', gap: '8px', border: '1px solid var(--border-color)' }}>
                  {metrics.harmonics.map((h) => {
                    const barHeight = Math.max(12, (h.magnitude / (metrics.vOutPeak || 1)) * 100);
                    return (
                      <div key={h.order} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px', flex: 1 }}>
                        <span style={{ fontSize: '0.68rem', color: 'var(--text-muted)' }}>{h.magnitude}V</span>
                        <div style={{ width: '100%', height: `${barHeight}px`, background: h.order === 1 ? 'var(--accent-cyan)' : 'var(--accent-amber)', borderRadius: '4px 4px 0 0' }} />
                        <span style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', fontWeight: 600 }}>{h.order}f0</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Adjustable Parameters Panel */}
            <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '10px', border: '1px solid var(--border-color)', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '14px' }}>
              <div>
                <label style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>
                  VCC Supply: <strong style={{ color: 'var(--accent-cyan)' }}>{params.vcc} V</strong>
                </label>
                <input
                  type="range"
                  min={5}
                  max={24}
                  value={params.vcc}
                  onChange={(e) => setParams({ ...params, vcc: Number(e.target.value) })}
                  style={{ width: '100%', accentColor: 'var(--accent-cyan)', cursor: 'pointer' }}
                />
              </div>

              <div>
                <label style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>
                  Vin Peak Amplitude: <strong style={{ color: 'var(--accent-cyan)' }}>{params.vinPeak} V</strong>
                </label>
                <input
                  type="range"
                  min={0.2}
                  max={5.0}
                  step={0.1}
                  value={params.vinPeak}
                  onChange={(e) => setParams({ ...params, vinPeak: Number(e.target.value) })}
                  style={{ width: '100%', accentColor: 'var(--accent-cyan)', cursor: 'pointer' }}
                />
              </div>

              <div>
                <label style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>
                  Load Resistance (RL): <strong style={{ color: 'var(--accent-cyan)' }}>{params.rLoad} Ω</strong>
                </label>
                <input
                  type="range"
                  min={4}
                  max={100}
                  step={4}
                  value={params.rLoad}
                  onChange={(e) => setParams({ ...params, rLoad: Number(e.target.value) })}
                  style={{ width: '100%', accentColor: 'var(--accent-cyan)', cursor: 'pointer' }}
                />
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: DC LOAD LINE & Q-POINT PLOTTER */}
        {activeTab === 'loadline' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', flex: 1, overflowY: 'auto' }}>
            <div style={{ background: 'var(--bg-card)', padding: '10px 14px', borderRadius: '8px', border: '1px solid var(--border-color)', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
              🎯 <strong style={{ color: 'var(--text-primary)' }}>DC Load Line Analysis:</strong> Plotting Collector Current (IC) vs Collector-Emitter Voltage (VCE) and active Q-Point position.
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: '14px' }}>
              {/* Loadline Plot */}
              <div style={{ background: '#020617', padding: '14px', borderRadius: '10px', border: '1px solid var(--border-color)' }}>
                <svg width="100%" height="240" viewBox="0 0 360 240">
                  {/* Axes */}
                  <line x1="40" y1="20" x2="40" y2="200" stroke="var(--text-muted)" strokeWidth="1.5" />
                  <line x1="40" y1="200" x2="340" y2="200" stroke="var(--text-muted)" strokeWidth="1.5" />

                  <text x="15" y="30" fill="var(--accent-cyan)" fontSize="10" fontWeight="600">IC (mA)</text>
                  <text x="300" y="218" fill="var(--accent-cyan)" fontSize="10" fontWeight="600">VCE (V)</text>

                  {/* DC Load Line (Cutoff (VCC, 0) to Saturation (0, ICsat)) */}
                  <line x1="40" y1="40" x2="320" y2="200" stroke="var(--accent-rose)" strokeWidth="2.5" strokeDasharray="4 2" />

                  {/* Saturation Point */}
                  <circle cx="40" cy="40" r="5" fill="var(--accent-amber)" />
                  <text x="50" y="45" fill="var(--accent-amber)" fontSize="9">IC(sat) = {metrics.iSatMa}mA</text>

                  {/* Cutoff Point */}
                  <circle cx="320" cy="200" r="5" fill="var(--accent-amber)" />
                  <text x="270" y="190" fill="var(--accent-amber)" fontSize="9">VCC = {metrics.vcc}V</text>

                  {/* Active Q-Point Marker */}
                  {(() => {
                    const qX = 40 + (metrics.vCeq / metrics.vcc) * 280;
                    const qY = 200 - (metrics.iCqMa / (metrics.iSatMa || 1)) * 160;
                    return (
                      <g>
                        <circle cx={qX} cy={qY} r="7" fill="var(--accent-cyan)" stroke="#fff" strokeWidth="2" />
                        <text x={qX + 10} y={qY - 5} fill="var(--accent-cyan)" fontSize="11" fontWeight="700">
                          Q ({metrics.vCeq}V, {metrics.iCqMa}mA)
                        </text>
                      </g>
                    );
                  })()}
                </svg>
              </div>

              {/* Q-Point Parameters */}
              <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '10px', border: '1px solid var(--border-color)', display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '0.8rem' }}>
                <div style={{ fontSize: '0.88rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>
                  Operating Point Summary
                </div>
                <div style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>
                  VCEQ (Voltage): <strong>{metrics.vCeq} V</strong>
                </div>
                <div style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>
                  ICQ (Current): <strong>{metrics.iCqMa} mA</strong>
                </div>
                <div style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>
                  Max Saturation Current: <strong>{metrics.iSatMa} mA</strong>
                </div>
                <div style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>
                  Conduction Angle: <strong>{metrics.conductionAngleDeg}°</strong>
                </div>
                <div style={{ color: 'var(--text-muted)', fontSize: '0.72rem', marginTop: '6px' }}>
                  Adjust VCC or Load Resistance on Tab 1 to observe live Q-point shifting along the DC load line.
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 3: MEASUREMENTS & RESULTS TABLE */}
        {activeTab === 'table' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', flex: 1, overflowY: 'auto' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={{ fontSize: '0.88rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                Quantitative Measurements & Results Table
              </div>
              <button
                onClick={handleExportLabReport}
                style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 12px', borderRadius: '8px', border: '1px solid var(--accent-cyan)', background: 'rgba(56, 189, 248, 0.15)', color: 'var(--accent-cyan)', fontSize: '0.8rem', fontWeight: 600, cursor: 'pointer' }}
              >
                <Download size={14} /> Export Practical Lab Report (.txt)
              </button>
            </div>

            <div style={{ borderRadius: '10px', border: '1px solid var(--border-color)', overflow: 'hidden', background: 'var(--bg-panel)' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>
                <thead>
                  <tr style={{ background: 'var(--bg-card)', borderBottom: '1px solid var(--border-color)', color: 'var(--accent-cyan)', textAlign: 'left' }}>
                    <th style={{ padding: '10px 14px' }}>Parameter Name</th>
                    <th style={{ padding: '10px 14px' }}>Symbol</th>
                    <th style={{ padding: '10px 14px' }}>Measured Value</th>
                    <th style={{ padding: '10px 14px' }}>Units / Formula</th>
                  </tr>
                </thead>
                <tbody>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>DC Supply Voltage</td>
                    <td style={{ padding: '8px 14px' }}>VCC</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-cyan)' }}>{metrics.vcc}</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>Volts (V)</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Load Resistance</td>
                    <td style={{ padding: '8px 14px' }}>RL</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-cyan)' }}>{metrics.rLoad}</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>Ohms (Ω)</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Input Signal Amplitude (Peak / RMS)</td>
                    <td style={{ padding: '8px 14px' }}>Vin(pk) / Vin(rms)</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-cyan)' }}>{metrics.vInPeak} V / {metrics.vInRms} V</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>Vin,rms = Vin,pk / √2</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Output Signal Amplitude (Peak / RMS)</td>
                    <td style={{ padding: '8px 14px' }}>Vout(pk) / Vout(rms)</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-emerald)' }}>{metrics.vOutPeak} V / {metrics.vOutRms} V</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>Vout,rms = Vout,pk / √2</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Voltage Gain</td>
                    <td style={{ padding: '8px 14px' }}>Av / Av(dB)</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-emerald)' }}>{metrics.voltageGain}x ({metrics.voltageGainDb} dB)</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>20 log10(Vout/Vin)</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>AC Output Power</td>
                    <td style={{ padding: '8px 14px' }}>Pout</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-emerald)', fontWeight: 700 }}>{metrics.pOutMw} mW</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>Vout,rms² / RL</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>DC Supply Power</td>
                    <td style={{ padding: '8px 14px' }}>Pdc</td>
                    <td style={{ padding: '8px 14px' }}>{metrics.pDcMw} mW</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>VCC × IDC</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Transistor Power Dissipation (Heat)</td>
                    <td style={{ padding: '8px 14px' }}>Pd</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-rose)' }}>{metrics.pDissipationMw} mW</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>Pdc - Pout</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Collector Efficiency</td>
                    <td style={{ padding: '8px 14px' }}>η (%)</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-emerald)', fontWeight: 800, fontSize: '0.95rem' }}>{metrics.efficiency} %</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>(Pout / Pdc) × 100%</td>
                  </tr>
                  <tr>
                    <td style={{ padding: '8px 14px', fontWeight: 600 }}>Total Harmonic Distortion</td>
                    <td style={{ padding: '8px 14px' }}>THD (%)</td>
                    <td style={{ padding: '8px 14px', color: 'var(--accent-rose)' }}>{metrics.thdPercent} %</td>
                    <td style={{ padding: '8px 14px', color: 'var(--text-muted)' }}>√(H2² + H3² + ...) / H1</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* TAB 4: PRACTICAL WORKSHEET */}
        {activeTab === 'manual' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', flex: 1, overflowY: 'auto', fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
            <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '10px', border: '1px solid var(--border-color)' }}>
              <h3 style={{ fontSize: '0.92rem', color: 'var(--accent-cyan)', marginBottom: '8px' }}>
                📋 Lab Experiment Manual: Power Amplifier Characteristics
              </h3>
              <p style={{ marginBottom: '8px' }}>
                <strong>Objective:</strong> To study and compare the input vs output sine wave characteristics, conduction angles, efficiency, and distortion of Class A, Class B, Class AB, Class C, and Class D power amplifiers.
              </p>
              <ol style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <li>Select the target Power Amplifier class from the top selection buttons.</li>
                <li>Adjust the VCC Supply Voltage (VCC) and Load Resistance (RL).</li>
                <li>Vary the Input Signal Amplitude (Vin) and observe the output sine wave waveform on the Oscilloscope.</li>
                <li>Note the clipping point on the Vin vs Vout transfer curve.</li>
                <li>Compare measured collector efficiency against theoretical limits.</li>
              </ol>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
